application: micolog-tribe
version: 3
runtime: python
api_version: 1

builtins:
- admin_redirect: on
- appstats: on
- datastore_admin: on

inbound_services:
- xmpp_message
- warmup
- mail

handlers:
- url: /favicon\.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico
  mime_type: image/x-icon

- url: /static
  static_dir: static
  expiration: "30d"
  
- url: /remote_api
  script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py
  login: admin
  
- url: /admin/.*
  script: $PYTHON_LIB/google/appengine/ext/admin
  login: admin

- url: /.*
  script: main.py
