application: micolog-tribe
version: 8
runtime: python
api_version: 1

builtins:
- appstats: on

inbound_services:
- xmpp_message

handlers:
- url: /static
  static_dir: static
  expiration: "30d"

- url: /.*
  script: main.py
